### ISSUE TITLE
_this.resolveReadyUpPromise is not a function

### ISSUE THREAD

**Issue by Jameskmonger** [Jameskmonger/creature-chess#208]
```
 test readied up                                                                                                       
 /home/creaturechess/server/src/shared/game/player/player.ts:393                                                       
         this.resolveReadyUpPromise();                                                                                 
              ^                                                                                                        
 TypeError: _this.resolveReadyUpPromise is not a function                                                              
     at Socket.Player.readyUp (/home/creaturechess/server/src/shared/game/player/player.ts:393:14)                     
     at Socket.emit (events.js:198:13)                                                                                 
     at /home/creaturechess/server/node_modules/socket.io/lib/socket.js:528:12                                         
     at process._tickCallback (internal/process/next_tick.js:61:11)                                                    
 npm ERR! code ELIFECYCLE                                                                                              
 npm ERR! errno 1                                                                                                      
 npm ERR! creature-chess@1.0.0 start:server: `npm run build:server && node -r ts-node/register -r tsconfig-paths/regist
 npm ERR! Exit status 1                                                                                                
 npm ERR!                                                                                                              
 npm ERR! Failed at the creature-chess@1.0.0 start:server script.                                                      
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                    
 npm ERR! A complete log of this run can be found in:                                                                  
 npm ERR!     /root/.npm/_logs/2019-08-30T16_10_37_753Z-debug.log                                                      
 creaturechess-server.service: Main process exited, code=exited, status=1/FAILURE                                      
 creaturechess-server.service: Failed with result 'exit-code'.                                                         
```

**Comment by Jameskmonger** [comment]
This code is all basically a roll-your-own version of https://www.npmjs.com/package/p-defer and could be replaced
